apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "Lumina123"
    jsonData:
      sslmode: "disable" # disable