{
 "title": "Lumina",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Median Churn",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH user_interaction_counts AS (\n    SELECT\n        chat_id,\n        COUNT(*) AS message_count\n    FROM\n        public.interactions\n    GROUP BY\n        chat_id\n)\n\nSELECT\n    AVG(message_count) AS average_messages_before_stop\nFROM\n    user_interaction_counts;\n"
    }
   ]
  },
  {
   "title": "Unique IDs Per Day",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', timestamp) AS interaction_date, COUNT(DISTINCT chat_id) AS unique_ids_per_day\nFROM public.interactions\nGROUP BY interaction_date\nORDER BY interaction_date;\n"
    }
   ]
  },
  {
   "title": "Overall Unique Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT chat_id) AS overall_unique_ids\nFROM public.interactions;\n"
    }
   ]
  },
  {
   "title": "Phone Numbers /Day",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('day', i.timestamp) AS interaction_date,\n    i.chat_id AS unique_id,\n    COUNT(CASE WHEN i.message LIKE '%[0-9]%' THEN 1 END) AS received_phone_numbers_per_day\nFROM \n    public.interactions i\nGROUP BY \n    interaction_date, unique_id\nORDER BY \n    interaction_date, unique_id;\n"
    }
   ]
  },
  {
   "title": "Avg Messages Per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    u.user_id,\n    u.first_name,\n    u.last_name,\n    u.username,\n    COUNT(i.message) AS message_count,\n    AVG(COUNT(i.message)) OVER () AS average_messages_sent\nFROM \n    public.user_data u\nLEFT JOIN \n    public.interactions i ON u.user_id = i.chat_id\nGROUP BY \n    u.user_id, u.first_name, u.last_name, u.username\nORDER BY \n    u.user_id;\n"
    }
   ]
  },
  {
   "title": "Conversation Started",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT u.user_id, u.first_name, u.last_name, u.username, MIN(i.timestamp) AS conversation_started\nFROM public.user_data u\nJOIN public.interactions i ON u.user_id = i.chat_id\nGROUP BY u.user_id, u.first_name, u.last_name, u.username\nORDER BY u.user_id;\n"
    }
   ]
  },
  {
   "title": "User Come Back",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH user_interactions AS (\n    SELECT \n        chat_id,\n        \"timestamp\",\n        LAG(\"timestamp\") OVER (PARTITION BY chat_id ORDER BY \"timestamp\") AS previous_timestamp\n    FROM \n        public.interactions\n)\n\nSELECT \n    ud.user_id,\n    ud.first_name,\n    ud.last_name,\n    ud.username,\n    COUNT(ui.chat_id) AS come_back_count\nFROM \n    user_interactions ui\nJOIN \n    public.user_data ud ON ui.chat_id = ud.user_id\nWHERE \n    ui.\"timestamp\" - ui.previous_timestamp > INTERVAL '1 day' OR ui.previous_timestamp IS NULL\nGROUP BY \n    ud.user_id, ud.first_name, ud.last_name, ud.username\nORDER BY \n    ud.user_id;\n"
    }
   ]
  }
 ]
}